### ISSUE TITLE
Give consideration to a less restrictive license

### ISSUE THREAD

**Issue by indiescripter** [Typeverse/enumset32#1]
Several developers have raised the subject of licensing *enumset32* under a less restrictive license via private Twitter messages to [The Typeverse Project](https://twitter.com/typeverse).

The main issue seems to be that people are concerned that the **GPL-3.0** is restrictive about allowing the JavaScript code to be *statically-linked* in their web/browser client-side applications with, say, **webpack** (even though it's not a problem for it to be *dynamically-linked* or *require'd* in **Node.js** server-side apps).

The Typeverse Project is only just starting out to release a number of TypeScript/JavaScript packages of which *enumset32* is the first. There was no intention to stop people from using *enumset32* in browser applications when the GPL-3.0 license was originally chosen as including the library in a web page via a <script> tag counts as *dynamic-linking* which is okay.

It turns out, though, that bundling the library via **webpack**, **rollup** and the like counts as *static-linking*. This is problematic as it discourages use of *enumset32* from a licensing point of view.

Digging into this, it appears that there is a lot to like about the both the **LGPL** (Lesser GPL) and **MPL** (Mozilla Public License). Adopting one of these licenses would help to make sure that changes and code improvements get back to the community whereas the **MIT** license would be too permissive.

A link to this issue will be posted on Twitter to solicit feedback.

If you are reading this and have a suggestion for a weak copyleft license that does not hinder use of *enumset32* in the browser **please tell** by commenting here or by replying to [this thread on Twitter](https://twitter.com/typeverse/status/1137142695170699264).

**Comment by indiescripter** [comment]
Hey Enumset32 Stargazers,

- @bleshik
- @faustbrian
- @gasparandr
- @joewood
- @juanpicado
- @UnknownHero

If you are able to contribute any comments or feedback on this issue about choosing a license for *enumset32*, that would be greatly appreciated.

Thanks!

Justin Johansson
@indiescripter

**Comment by bleshik** [comment]
Why not Apache license 2.0?

**Comment by juanpicado** [comment]
@bleshik Apache License 2.0 is almost the same as MIT, but with the difference of to have a patent grant defined.  I think @indiescripter is suggesting something that allows him to get back any change that anyone does to the library. 

I was reading https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses 
and I think **MPL** fits better in your purpose @indiescripter .

**Comment by indiescripter** [comment]
Thanks @bleshik & @juanpicado for quickly chiming in.

cc/ @faustbrian @gasparandr @joewood @UnknownHero

I've been digging deep into this subject today and came up with [a package on npmjs called exifreader](https://www.npmjs.com/package/exifreader) which is **MPL**.

Last published 2 months ago, *ExifReader* is getting a steady trickle of downloads (>1K per week). Whilst that number is hardly a torrent, it suggests to me that people are willing (and can legally) use **MPL** licensed code within a larger **MIT** licensed work. More likely the relatively small number of downloads is to do with lack of visibility & "marketing" than anything else.

Anyway I found *ExifReader* by doing a google search with the specifier `site:github.com` added to my search terms and found [this issue](https://github.com/mattiasw/ExifReader/issues/33) addressing exactly the same concerns raised here.

Salient points from that *ExifReader* thread are:

> I agree with you, LGPL will not allow the library to be used in a closed-source mobile app. At least not without a lot of hassle from the app developer. I will change the license. Not sure to which one yet though. I like everything else about the LGPL and I think e.g. MIT would be too permissive. I would like to make sure changes get back to the community e.g. If you have a suggestion for a license, please tell me. -- @mattiasw (ExifReader author)

> Awesome! The Mozilla Public License may have that right balance. Reading it myself this wasn’t 100% clear, but the summary at https://choosealicense.com/licenses/ suggests that it is less limiting on “larger works.” -- @mike-marcacci (ExifReader user who asked the question)

> After reading up on MPL it sounds perfect. Thanks! -- @mattiasw (ExifReader author)

> Updated and published. -- @mattiasw (ExifReader author)

All-in-all this rhymes with @juanpicado's comments:

> @bleshik Apache License 2.0 is almost the same as MIT (too permissive), but with the difference of to have a patent grant defined. I think @indiescripter is suggesting something that allows him to get back any change that anyone does to the library.

> I was reading https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
and I think MPL fits better in your purpose @indiescripter .

See also: [Can I include code licensed under MPL within a project under MIT license?](https://softwareengineering.stackexchange.com/questions/317944/can-i-include-code-licensed-under-mpl-within-a-project-under-mit-license) which accepted answer says **"Yes you can"** :D.

Sweet, I'll update and publish *enumset32* under **MPL-2.0** as soon as possible.

Thanks again to all those reading & contributing to this topic.

Justin Johansson
Twitter: [@IndieScripter](https://twitter.com/IndieScripter)

The Typeverse Project
Twitter: [@typeverse](https://twitter.com/typeverse)

**Comment by indiescripter** [comment]
[License updated to MPL-2.0](https://github.com/Typeverse/enumset32/commit/f665b0e5748a5e75d3d561a73793b82d3be763af) and published to [npmjs.com](https://www.npmjs.com/package/enumset32) as v0.6.0

**Comment by juanpicado** [comment]
A license change would be a breaking change, but since it is under 1.0.0 I think is ok.

**Comment by typeversity** [comment]
Thanks for input & agree @juanpicado that it normally would be. But, yeah, since it's under 1.0.0 should be ok. Haven't seen any dependents on npmjs.com yet.
